on: [pull_request]
name: Test
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Setup golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install Requirements
        run: |
          GO111MODULES=off; go mod vendor
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
      - name: Setup SSH Key Build and run e2e
        run : |
          make e2e-build
          make e2e-run
          make install-shellcheck
        shell: bash
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          GIT_TOKEN: ${{secrets.GIT_TOKEN}}
          GIT_USER: ${{secrets.GIT_USER}}
      - name: Test e2e
        run: |
          make check
          make e2e-test
      - name: Clean e2e
        run: |
          make e2e-stop
